//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneGovernment
{
    public partial class ForgotPassword
    {
        // Step panels
        protected global::System.Web.UI.WebControls.Panel pnlStep1;
        protected global::System.Web.UI.WebControls.Panel pnlStep2;
        protected global::System.Web.UI.WebControls.Panel pnlStep3;
        protected global::System.Web.UI.WebControls.Panel pnlStep4;

        // Step indicator dots
        protected global::System.Web.UI.WebControls.Panel dot1;
        protected global::System.Web.UI.WebControls.Panel dot2;
        protected global::System.Web.UI.WebControls.Panel dot3;
        protected global::System.Web.UI.WebControls.Panel dot4;

        // Step 1 controls
        protected global::System.Web.UI.WebControls.Label lblStep1Error;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.Button btnSendOTP;

        // Step 2 controls
        protected global::System.Web.UI.WebControls.Label lblOtpEmail;
        protected global::System.Web.UI.WebControls.Label lblDemoOTP;
        protected global::System.Web.UI.WebControls.Label lblOtpError;
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnOTPValue_inner;
        protected global::System.Web.UI.WebControls.HiddenField hdnOTPValue;
        protected global::System.Web.UI.WebControls.Button btnVerifyOTP;
        protected global::System.Web.UI.WebControls.Button btnResendOTP;

        // Step 3 controls
        protected global::System.Web.UI.WebControls.Label lblStep3Error;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewPw;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmPw;
        protected global::System.Web.UI.WebControls.CompareValidator cvPasswords;
        protected global::System.Web.UI.WebControls.Button btnResetPassword;
    }
}
