//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneGovernment.Banking_From
{
    public partial class BankingDetails
    {
        protected global::System.Web.UI.WebControls.Button btnOverview;
        protected global::System.Web.UI.WebControls.Button btnLinks;
        protected global::System.Web.UI.WebControls.Button btnDocuments;
        protected global::System.Web.UI.WebControls.Button btnDemoForm;
        protected global::System.Web.UI.WebControls.MultiView mvDetails;
        protected global::System.Web.UI.WebControls.View viewOverview;
        protected global::System.Web.UI.WebControls.View viewLinks;
        protected global::System.Web.UI.WebControls.View viewDocuments;
        protected global::System.Web.UI.WebControls.View viewDemoForm;
        protected global::System.Web.UI.WebControls.Image imgDemoForm;
    }
}
